CREATE TABLE categories (
    id CHAR(36) NOT NULL,
    name VARCHAR(255) NOT NULL,
    parent CHAR(36),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    FOREIGN KEY (parent) REFERENCES categories(id) ON DELETE SET NULL
);